### ISSUE TITLE
/app/graphql/resolvers/timeline.go:48 ERROR: function year(timestamp with time zone) does not exist (SQLSTATE 42883)

### ISSUE THREAD

**Issue by g3n3r0s0** [photoview/photoview#194]
Hi,

I got this error after login, when main page is displayed.

I installed latest docker image (2.1) and configured container with Postgres DB (postgres:13 image).
Environment is Debian 10 (Open Media Vault) in VMWare machine.

Hope this can help.

Thanks,
Gab

```
2021/02/13 17:01:40 /app/graphql/resolvers/timeline.go:48 ERROR: function year(timestamp with time zone) does not exist (SQLSTATE 42883),
[1.644ms] [rows:-] SELECT albums.id AS album_id,YEAR(media.date_shot) AS year,MONTH(media.date_shot) AS month,DAY(media.date_shot) AS day FROM "media" JOIN albums ON media.album_id = albums.id WHERE albums.id IN (SELECT user_albums.album_id FROM "user_albums" WHERE user_id = 1) GROUP BY albums.id, YEAR(media.date_shot), MONTH(media.date_shot), DAY(media.date_shot) ORDER BY media.date_shot DESC LIMIT 50,
runtime error: invalid memory address or nil pointer dereference,
,
goroutine 51 [running]:,
runtime/debug.Stack(0x1, 0x0, 0x0),
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9f,
ntime/debug.PrintStack(),
	/usr/local/go/src/runtime/debug/stack.go:16 +0x25,
github.com/99designs/gqlgen/graphql.DefaultRecover(0xe6ae40, 0xc000463890, 0xcb3760, 0x1239260, 0x0, 0x41d834),
	/go/pkg/mod/github.com/99designs/gqlgen@v0.13.0/graphql/recovery.go:16 +0xaa,
github.com/99designs/gqlgen/graphql.(*OperationContext).Recover(0xc00041e800, 0xe6ae40, 0xc000463890, 0xcb3760, 0x1239260, 0xc0000e84b0, 0x0),
	/go/pkg/mod/github.com/99designs/gqlgen@v0.13.0/graphql/context_operation.go:110 +0x56,
github.com/photoview/photoview/api/graphql.(*executionContext)._Query_myTimeline.func1(0xc000033d30, 0xc000033d80, 0xc0000e8c70),
	/app/graphql/generated.go:5277 +0x79,
panic(0xcb3760, 0x1239260),
	/usr/local/go/src/runtime/panic.go:969 +0x1b9,
database/sql.(*Rows).close(0x0, 0x0, 0x0, 0x0, 0x0),
	/usr/local/go/src/database/sql/sql.go:3155 +0x76,
database/sql.(*Rows).Close(0x0, 0x0, 0xe547e0),
	/usr/local/go/src/database/sql/sql.go:3151 +0x33,
github.com/photoview/photoview/api/graphql/resolvers.(*queryResolver).MyTimeline.func1(0xc000463ad0, 0xe547e0, 0xc000366000),
	/app/graphql/resolvers/timeline.go:53 +0x10cb,
gorm.io/gorm.(*DB).Transaction(0xc0001fc870, 0xc000463a10, 0x0, 0x0, 0x0, 0x0, 0x0),
	/go/pkg/mod/gorm.io/gorm@v1.20.12/finisher_api.go:552 +0x3da,
github.com/photoview/photoview/api/graphql/resolvers.(*queryResolver).MyTimeline(0xc0002f43a8, 0xe6ae40, 0xc000463890, 0xc000033db0, 0xc0004389d0, 0x20, 0x20, 0x7f4b18bb6108, 0xc00000fa60, 0xc0003d8998),
	/app/graphql/resolvers/timeline.go:20 +0x114,
github.com/photoview/photoview/api/graphql.(*executionContext)._Query_myTimeline.func2(0xe6ae40, 0xc000463890, 0x20, 0xd08820, 0xc000033d01, 0xc00000fa60),
	/app/graphql/generated.go:5299 +0x162,
github.com/99designs/gqlgen/graphql/executor.processExtensions.func3(0xe6ae40, 0xc000463890, 0xc00000fa60, 0xc0004638c0, 0xc000463920, 0x0, 0x0),
	/go/pkg/mod/github.com/99designs/gqlgen@v0.13.0/graphql/executor/extensions.go:62 +0x3a,
github.com/photoview/photoview/api/graphql.(*executionContext)._Query_myTimeline(0xc000033d30, 0xe6ae40, 0xc000463860, 0xc0000e3180, 0xc00007a690, 0x5, 0x5, 0x0, 0x0),
	/app/graphql/generated.go:5297 +0x2d8,
github.com/photoview/photoview/api/graphql.(*executionContext)._Query.func9(0x0, 0x0),
	/app/graphql/generated.go:8762 +0xa8,
github.com/99designs/gqlgen/graphql.(*FieldSet).Dispatch(0xc00007a730),
	/go/pkg/mod/github.com/99designs/gqlgen@v0.13.0/graphql/fieldset.go:34 +0x1dd,
github.com/photoview/photoview/api/graphql.(*executionContext)._Query(0xc000033d30, 0xe6ae40, 0xc000463830, 0xc000033a50, 0x1, 0x1, 0xc000463830, 0x30),
	/app/graphql/generated.go:8843 +0x486,
github.com/photoview/photoview/api/graphql.(*executableSchema).Exec.func1(0xe6ae40, 0xc000463830, 0x10),
	/app/graphql/generated.go:1292 +0x7b,
github.com/99designs/gqlgen/graphql/executor.(*Executor).DispatchOperation.func1.1.1(0xe6ae40, 0xc000463830, 0xc000033d40),
	/go/pkg/mod/github.com/99designs/gqlgen@v0.13.0/graphql/executor/executor.go:105 +0x43,
github.com/99designs/gqlgen/graphql/executor.processExtensions.func2(0xe6ae40, 0xc000463830, 0xc000033d40, 0xe414c0),
	/go/pkg/mod/github.com/99designs/gqlgen@v0.13.0/graphql/executor/extensions.go:59 +0x3a,
github.com/99designs/gqlgen/graphql/executor.(*Executor).DispatchOperation.func1.1(0xe6ae40, 0xc0004637d0, 0xc000463710),
	/go/pkg/mod/github.com/99designs/gqlgen@v0.13.0/graphql/executor/executor.go:104 +0x12c,
github.com/99designs/gqlgen/graphql/handler/transport.POST.Do(0xe62b80, 0xc0004628a0, 0xc00041e700, 0xe61140, 0xc0003bddd0),
	/go/pkg/mod/github.com/99designs/gqlgen@v0.13.0/graphql/handler/transport/http_post.go:53 +0x3a8,
github.com/99designs/gqlgen/graphql/handler.(*Server).ServeHTTP(0xc0003ec320, 0xe62b80, 0xc0004628a0, 0xc00041e700),
	/go/pkg/mod/github.com/99designs/gqlgen@v0.13.0/graphql/handler/server.go:115 +0x21b,
net/http.HandlerFunc.ServeHTTP(0xc0003dbba0, 0xe62b80, 0xc0004628a0, 0xc00041e600),
	/usr/local/go/src/net/http/server.go:2042 +0x44,
github.com/photoview/photoview/api/server.CORSMiddleware.func1.1(0xe62b80, 0xc0004628a0, 0xc00041e600),
	/app/server/cors_middleware.go:39 +0x970,
net/http.HandlerFunc.ServeHTTP(0xc00000e680, 0xe62b80, 0xc0004628a0, 0xc00041e600),
	/usr/local/go/src/net/http/server.go:2042 +0x44,
github.com/photoview/photoview/api/server.LoggingMiddleware.func1(0xe64280, 0xc00007a230, 0xc00041e600),
	/app/server/logging.go:20 +0x152,
net/http.HandlerFunc.ServeHTTP(0xc00000e6a0, 0xe64280, 0xc00007a230, 0xc00041e600),
	/usr/local/go/src/net/http/server.go:2042 +0x44,
github.com/photoview/photoview/api/graphql/auth.Middleware.func1.1(0xe64280, 0xc00007a230, 0xc00041e500),
	/app/graphql/auth/auth.go:49 +0x307,
net/http.HandlerFunc.ServeHTTP(0xc00000e6c0, 0xe64280, 0xc00007a230, 0xc00041e500),
	/usr/local/go/src/net/http/server.go:2042 +0x44,
github.com/photoview/photoview/api/graphql/dataloader.Middleware.func1.1(0xe64280, 0xc00007a230, 0xc00041e400),
	/app/graphql/dataloader/loaders.go:35 +0x2a7,
net/http.HandlerFunc.ServeHTTP(0xc00000e6e0, 0xe64280, 0xc00007a230, 0xc00041e400),
	/usr/local/go/src/net/http/server.go:2042 +0x44,
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0001fa480, 0xe64280, 0xc00007a230, 0xc00041e100),
	/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3,
github.com/gorilla/handlers.CompressHandlerLevel.func1(0xe63300, 0xc000206000, 0xc00041e100),
	/go/pkg/mod/github.com/gorilla/handlers@v1.5.1/compress.go:141 +0x692,
net/http.HandlerFunc.ServeHTTP(0xc0003ec740, 0xe63300, 0xc000206000, 0xc00041e100),
	/usr/local/go/src/net/http/server.go:2042 +0x44,
net/http.serverHandler.ServeHTTP(0xc000206540, 0xe63300, 0xc000206000, 0xc00041e100),
	/usr/local/go/src/net/http/server.go:2843 +0xa3,
net/http.(*conn).serve(0xc000420140, 0xe6ad80, 0xc000454180),
	/usr/local/go/src/net/http/server.go:1925 +0x8ad,
created by net/http.(*Server).Serve,
	/usr/local/go/src/net/http/server.go:2969 +0x36c,

```

**Comment by viktorstrate** [comment]
Hi @g3n3r0s0 thank you for reporting, it looks like Postgres doesn't support the `YEAR` function. I guess I haven't tested the changes properly with all database backends.

**Comment by g3n3r0s0** [comment]
I didn't test, but the best approach seems to use EXTRACT() in place of Year Month and Day, which is cross to both MySQL and Postgres:
EXTRACT(YEAR FROM media.date_shot)

**Comment by g3n3r0s0** [comment]
I made these 2 fixes and tested only with Postgres:

```
/app/graphql/resolvers/timeline.go
46 		rows, err := daysQuery.Group("albums.id, **EXTRACT(YEAR FROM media.date_shot), EXTRACT(MONTH FROM media.date_shot), EXTRACT(DAY FROM media.date_shot)**").
47 			Order("**EXTRACT(YEAR FROM media.date_shot) DESC, EXTRACT(MONTH FROM media.date_shot) DESC, EXTRACT(DAY FROM media.date_shot) DESC**").
48 			Rows()
```

```
/app/graphql/dataloader/userFavoriteLoader.go
39 			err := db.Where("user_id IN (?)", uniqueUserIDs).Where("media_id IN (?)", uniqueMediaIDs).Where("favorite = **true**").Find(&userMediaFavorites).Error

```

**Comment by g3n3r0s0** [comment]
Hi @viktorstrate, thanks for the fix, this is a follow up:

- These is a typo "postgress" in the api/database/helpers.go
26 	case "mysql", "postgress":

- Postgres is more rigid that MySQL, I guess, but the "media.date_shot" cannot be in the group by (while in MySQL works):
2021/02/14 10:39:25 /app/graphql/resolvers/timeline.go:55 ERROR: column "media.date_shot" must appear in the GROUP BY clause or be used in an aggregate function (SQLSTATE 42803)

**Comment by g3n3r0s0** [comment]
I see you fixed in the meanwhile, I'll test it! :-)

**Comment by viktorstrate** [comment]
Yes, I think it should work now for all supported database backends.
Let me know when you're finished and if you find anything.

**Comment by g3n3r0s0** [comment]
It seems working fine for both postgres and mysql!
Thanks for quick fixes, really appreciated.

**Comment by viktorstrate** [comment]
No issue, thank you for taking the time to report and test it
