### ISSUE TITLE
Access denied for user 'photoview'@'tcp(db)' while using Docker compose

### ISSUE THREAD

**Issue by bhm** [photoview/photoview#441]
**Description**
Current `docker-compose.example.yml` and instructions in repository do not allow to easily deploy an instance.    

**To Reproduce**
1. Install docker for arm64/v8 or amd64 (Environments section)
2. Create user 'photoview' and add him to `docker` group
3. Create `docker` dir in `photoview` user home directory.
4. Navigate to docker directory
5. Create `docker-compose.yml` file with contents (Environments section)
6. Issue `docker-compose up -d`

**Expected behavior**  
docker compose deploys a working instance

**Actual**
1. Photoview container restarts every 24 seconds. See Error Logs
2. Database container is not setup with correct users credentials. Neither of `root`, `photoview`, `root@%`, `photoview@%`, `root@CONTAINER_IP`, `photoview@CONTAINER_ID` is accessble after dropping into containers shell.
3. Database container does not allow Photoview container to access mysql instance. See log.

**Environments**
This was tested across two different machines. Armbian Buster on an arm64 board and Debian Buster on an amd64 platform.

#### Armbian Docker
```
Client: Docker Engine - Community
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        f0df350
 Built:             Wed Jun  2 11:57:26 2021
 OS/Arch:           linux/arm64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:55:36 2021
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

#### Debian Docker
```
Client: Docker Engine - Community
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        f0df350
 Built:             Wed Jun  2 11:56:47 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:54:58 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

#### docker-compose.yml
```
version: "3.2"

services:
  db:
    image: mariadb:10.5.11
    restart: always
    environment:
      - MARIADB_DATABASE="photoview"
      - MARIADB_USER="photoview"
      - MARIADB_PASSWORD="1234"
      - MARIADB_ROOT_PASSWORD="root"
    volumes:
      - db_data:/var/lib/mysql

  photoview:
    image: viktorstrate/photoview:2.3.4
    restart: always
    ports:
      - "8000:80"
    depends_on:
      - db

    environment:
      - PHOTOVIEW_DATABASE_DRIVER=mysql
      - PHOTOVIEW_MYSQL_URL=photoview:1234@tcp(db)/photoview
      - PHOTOVIEW_LISTEN_IP=photoview
      - PHOTOVIEW_LISTEN_PORT=80
      - PHOTOVIEW_MEDIA_CACHE=/app/cache

      # Optional: If you are using Samba/CIFS-Share and experience problems with "directory not found"
      # Enable the following Godebug
      # - GODEBUG=asyncpreemptoff=1


      # Optional: To enable map related features, you need to create a mapbox token.
      # A token can be generated for free here https://account.mapbox.com/access-tokens/
      # It's a good idea to limit the scope of the token to your own domain, to prevent others from using it.
      # - MAPBOX_TOKEN=<YOUR TOKEN HERE>

    volumes:
      - api_cache:/app/cache

      # Change This: to the directory where your photos are located on your server.
      # If the photos are located at `/home/user/photos`, then change this value
      # to the following: `/home/user/photos:/photos:ro`.
      # You can mount multiple paths, if your photos are spread across multiple directories.
      - /actual/path/to/dir/with/access:/photos:ro

volumes:
  db_data:
  api_cache:
```

**Error Log: Database**
```shell
docker logs --timestamps --follow --tail=50 docker_db_1
2021-07-19T21:34:31.318091355Z 2021-07-19 21:34:31 0 [Note] InnoDB: Initializing buffer pool, total size = 134217728, chunk size = 134217728
2021-07-19T21:34:31.323449506Z 2021-07-19 21:34:31 0 [Note] InnoDB: Completed initialization of buffer pool
2021-07-19T21:34:31.342032651Z 2021-07-19 21:34:31 0 [Note] InnoDB: 128 rollback segments are active.
2021-07-19T21:34:31.344397979Z 2021-07-19 21:34:31 0 [Note] InnoDB: Creating shared tablespace for temporary tables
2021-07-19T21:34:31.344471966Z 2021-07-19 21:34:31 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
2021-07-19T21:34:31.344576496Z 2021-07-19 21:34:31 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
2021-07-19T21:34:31.346791520Z 2021-07-19 21:34:31 0 [Note] InnoDB: 10.5.11 started; log sequence number 45118; transaction id 20
2021-07-19T21:34:31.346994171Z 2021-07-19 21:34:31 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
2021-07-19T21:34:31.347114143Z 2021-07-19 21:34:31 0 [Note] Plugin 'FEEDBACK' is disabled.
2021-07-19T21:34:31.348691296Z 2021-07-19 21:34:31 0 [Note] InnoDB: Buffer pool(s) load completed at 210719 21:34:31
2021-07-19T21:34:31.353025680Z 2021-07-19 21:34:31 0 [Note] Server socket created on IP: '::'.
2021-07-19T21:34:31.354566343Z 2021-07-19 21:34:31 0 [Warning] 'proxies_priv' entry '@% root@df3751870a00' ignored in --skip-name-resolve mode.
2021-07-19T21:34:31.382214701Z 2021-07-19 21:34:31 0 [Note] Reading of all Master_info entries succeeded
2021-07-19T21:34:31.382242813Z 2021-07-19 21:34:31 0 [Note] Added new Master_info '' to hash table
2021-07-19T21:34:31.382253837Z 2021-07-19 21:34:31 0 [Note] mysqld: ready for connections.
2021-07-19T21:34:31.382266933Z Version: '10.5.11-MariaDB-1:10.5.11+maria~focal'  socket: '/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
2021-07-19T21:34:34.051748058Z 2021-07-19 21:34:34 3 [Warning] Access denied for user 'photoview'@'172.19.0.3' (using password: YES)
2021-07-19T21:34:39.054865213Z 2021-07-19 21:34:39 4 [Warning] Access denied for user 'photoview'@'172.19.0.3' (using password: YES)
2021-07-19T21:34:44.057866502Z 2021-07-19 21:34:44 5 [Warning] Access denied for user 'photoview'@'172.19.0.3' (using password: YES)
2021-07-19T21:34:49.945388241Z 2021-07-19 21:34:49 6 [Warning] Access denied for user 'photoview'@'172.19.0.3' (using password: YES)
2021-07-19T21:34:54.948114905Z 2021-07-19 21:34:54 7 [Warning] Access denied for user 'photoview'@'172.19.0.3' (using password: YES)
2021-07-19T21:34:59.951025052Z 2021-07-19 21:34:59 8 [Warning] Access denied for user 'photoview'@'172.19.0.3' (using password: YES)
2021-07-19T21:35:04.955508341Z 2021-07-19 21:35:04 9 [Warning] Access denied for user 'photoview'@'172.19.0.3' (using password: YES)
2021-07-19T21:35:09.958567421Z 2021-07-19 21:35:09 10 [Warning] Access denied for user 'photoview'@'172.19.0.3' (using password: YES)
2021-07-19T21:35:15.849004293Z 2021-07-19 21:35:15 11 [Warning] Access denied for user 'photoview'@'172.19.0.3' (using password: YES)
2021-07-19T21:35:20.851804692Z 2021-07-19 21:35:20 12 [Warning] Access denied for user 'photoview'@'172.19.0.3' (using password: YES)
2021-07-19T21:35:25.854723037Z 2021-07-19 21:35:25 13 [Warning] Access denied for user 'photoview'@'172.19.0.3' (using password: YES)
2021-07-19T21:35:30.857579663Z 2021-07-19 21:35:30 14 [Warning] Access denied for user 'photoview'@'172.19.0.3' (using password: YES)
2021-07-19T21:35:35.860512354Z 2021-07-19 21:35:35 15 [Warning] Access denied for user 'photoview'@'172.19.0.3' (using password: YES)
2021-07-19T21:35:41.761026374Z 2021-07-19 21:35:41 16 [Warning] Access denied for user 'photoview'@'172.19.0.3' (using password: YES)
```

**Error Log: App**
```shell
 docker logs --timestamps --follow --tail=50 docker_photoview_1
2021-07-19T22:13:48.024364047Z 2021/07/19 22:13:48 WARN: Could not ping database: Error 1045: Access denied for user 'photoview'@'172.19.0.3' (using password: YES). Will retry after 5 seconds
2021-07-19T22:13:53.024937253Z 2021/07/19 22:13:53 Connecting to MYSQL database: photoview:1234@tcp(db:3306)/photoview?multiStatements=true&parseTime=true
2021-07-19T22:13:53.027350172Z
2021-07-19T22:13:53.027408110Z 2021/07/19 22:13:53 /app/database/database.go:101
2021-07-19T22:13:53.027422280Z [error] failed to initialize database, got error Error 1045: Access denied for user 'photoview'@'172.19.0.3' (using password: YES)
2021-07-19T22:13:53.027379031Z 2021/07/19 22:13:53 WARN: Could not ping database: Error 1045: Access denied for user 'photoview'@'172.19.0.3' (using password: YES). Will retry after 5 seconds
2021-07-19T22:13:58.027964268Z 2021/07/19 22:13:58 Connecting to MYSQL database: photoview:1234@tcp(db:3306)/photoview?multiStatements=true&parseTime=true
2021-07-19T22:13:58.030257589Z 2021/07/19 22:13:58 WARN: Could not ping database: Error 1045: Access denied for user 'photoview'@'172.19.0.3' (using password: YES). Will retry after 5 seconds
2021-07-19T22:13:58.030298894Z
2021-07-19T22:13:58.030330978Z 2021/07/19 22:13:58 /app/database/database.go:101
2021-07-19T22:13:58.030342903Z [error] failed to initialize database, got error Error 1045: Access denied for user 'photoview'@'172.19.0.3' (using password: YES)
2021-07-19T22:14:03.030862804Z 2021/07/19 22:14:03 Connecting to MYSQL database: photoview:1234@tcp(db:3306)/photoview?multiStatements=true&parseTime=true
2021-07-19T22:14:03.033115614Z
2021-07-19T22:14:03.033730442Z 2021/07/19 22:14:03 /app/database/database.go:101
2021-07-19T22:14:03.033750147Z [error] failed to initialize database, got error Error 1045: Access denied for user 'photoview'@'172.19.0.3' (using password: YES)
2021-07-19T22:14:03.033168500Z 2021/07/19 22:14:03 WARN: Could not ping database: Error 1045: Access denied for user 'photoview'@'172.19.0.3' (using password: YES). Will retry after 5 seconds
2021-07-19T22:14:08.036533639Z panic: runtime error: invalid memory address or nil pointer dereference
2021-07-19T22:14:08.036619247Z [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x807846]
2021-07-19T22:14:08.036645849Z
2021-07-19T22:14:08.036657809Z goroutine 1 [running]:
2021-07-19T22:14:08.036668928Z gorm.io/gorm.(*DB).getInstance(0x0, 0xa1)
2021-07-19T22:14:08.036679181Z  /go/pkg/mod/gorm.io/gorm@v1.21.6/gorm.go:346 +0x26
2021-07-19T22:14:08.036723173Z gorm.io/gorm.(*DB).SetupJoinTable(0x0, 0xe02fe0, 0xc0003ce000, 0xeb6d63, 0x6, 0xd9ac20, 0xc000380200, 0xc00016d470, 0x52b0ad)
2021-07-19T22:14:08.036735544Z  /go/pkg/mod/gorm.io/gorm@v1.21.6/gorm.go:376 +0x45
2021-07-19T22:14:08.036745804Z github.com/photoview/photoview/api/database.MigrateDatabase(0x0, 0x0, 0x0)
2021-07-19T22:14:08.036756021Z  /app/database/database.go:172 +0x9d
2021-07-19T22:14:08.036766074Z main.main()
2021-07-19T22:14:08.036775736Z  /app/server.go:46 +0x15f
2021-07-19T22:14:08.937983508Z 2021/07/19 22:14:08 Starting Photoview...
2021-07-19T22:14:08.938048918Z 2021/07/19 22:14:08 No .env file found
2021-07-19T22:14:08.938062911Z 2021/07/19 22:14:08 Connecting to MYSQL database: photoview:1234@tcp(db:3306)/photoview?multiStatements=true&parseTime=true
2021-07-19T22:14:08.940745867Z
2021-07-19T22:14:08.940785016Z 2021/07/19 22:14:08 /app/database/database.go:101
2021-07-19T22:14:08.940802205Z [error] failed to initialize database, got error Error 1045: Access denied for user 'photoview'@'172.19.0.3' (using password: YES)
2021-07-19T22:14:08.940793773Z 2021/07/19 22:14:08 WARN: Could not ping database: Error 1045: Access denied for user 'photoview'@'172.19.0.3' (using password: YES). Will retry after 5 seconds
2021-07-19T22:14:13.941295216Z 2021/07/19 22:14:13 Connecting to MYSQL database: photoview:1234@tcp(db:3306)/photoview?multiStatements=true&parseTime=true
2021-07-19T22:14:13.943546149Z
2021-07-19T22:14:13.945159159Z 2021/07/19 22:14:13 /app/database/database.go:101
2021-07-19T22:14:13.943604565Z 2021/07/19 22:14:13 WARN: Could not ping database: Error 1045: Access denied for user 'photoview'@'172.19.0.3' (using password: YES). Will retry after 5 seconds
2021-07-19T22:14:13.945198124Z [error] failed to initialize database, got error Error 1045: Access denied for user 'photoview'@'172.19.0.3' (using password: YES)
2021-07-19T22:14:18.944181176Z 2021/07/19 22:14:18 Connecting to MYSQL database: photoview:1234@tcp(db:3306)/photoview?multiStatements=true&parseTime=true
2021-07-19T22:14:18.946179063Z
2021-07-19T22:14:18.947260217Z 2021/07/19 22:14:18 /app/database/database.go:101
2021-07-19T22:14:18.946215401Z 2021/07/19 22:14:18 WARN: Could not ping database: Error 1045: Access denied for user 'photoview'@'172.19.0.3' (using password: YES). Will retry after 5 seconds
2021-07-19T22:14:18.947282923Z [error] failed to initialize database, got error Error 1045: Access denied for user 'photoview'@'172.19.0.3' (using password: YES)
2021-07-19T22:14:23.946818825Z 2021/07/19 22:14:23 Connecting to MYSQL database: photoview:1234@tcp(db:3306)/photoview?multiStatements=true&parseTime=true
2021-07-19T22:14:23.949196579Z
2021-07-19T22:14:23.950747591Z 2021/07/19 22:14:23 /app/database/database.go:101
2021-07-19T22:14:23.950766970Z [error] failed to initialize database, got error Error 1045: Access denied for user 'photoview'@'172.19.0.3' (using password: YES)
2021-07-19T22:14:23.949247636Z 2021/07/19 22:14:23 WARN: Could not ping database: Error 1045: Access denied for user 'photoview'@'172.19.0.3' (using password: YES). Will retry after 5 seconds
2021-07-19T22:14:28.949782188Z 2021/07/19 22:14:28 Connecting to MYSQL database: photoview:1234@tcp(db:3306)/photoview?multiStatements=true&parseTime=true
2021-07-19T22:14:28.952351100Z
2021-07-19T22:14:28.952965269Z 2021/07/19 22:14:28 /app/database/database.go:101
2021-07-19T22:14:28.952988226Z [error] failed to initialize database, got error Error 1045: Access denied for user 'photoview'@'172.19.0.3' (using password: YES)
2021-07-19T22:14:28.952378868Z 2021/07/19 22:14:28 WARN: Could not ping database: Error 1045: Access denied for user 'photoview'@'172.19.0.3' (using password: YES). Will retry after 5 seconds
2021-07-19T22:14:33.955794334Z panic: runtime error: invalid memory address or nil pointer dereference
2021-07-19T22:14:33.955919614Z [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x807846]
2021-07-19T22:14:33.955951569Z
2021-07-19T22:14:33.955967165Z goroutine 1 [running]:
2021-07-19T22:14:33.955980630Z gorm.io/gorm.(*DB).getInstance(0x0, 0xa1)
2021-07-19T22:14:33.955993791Z  /go/pkg/mod/gorm.io/gorm@v1.21.6/gorm.go:346 +0x26
2021-07-19T22:14:33.956007100Z gorm.io/gorm.(*DB).SetupJoinTable(0x0, 0xe02fe0, 0xc00030a460, 0xeb6d63, 0x6, 0xd9ac20, 0xc000214a40, 0xc00016d470, 0x52b0ad)
2021-07-19T22:14:33.956020578Z  /go/pkg/mod/gorm.io/gorm@v1.21.6/gorm.go:376 +0x45
2021-07-19T22:14:33.956033459Z github.com/photoview/photoview/api/database.MigrateDatabase(0x0, 0x0, 0x0)
2021-07-19T22:14:33.956046209Z  /app/database/database.go:172 +0x9d
2021-07-19T22:14:33.956058852Z main.main()
2021-07-19T22:14:33.956071085Z  /app/server.go:46 +0x15f
```

 - Database: [mariadb 10.5-11, 10.5]
 - Versions: [ 2, 2.3.4]

**Additional context**
 `MYSQL_` or `MARIADB_` prefix in params has no bearing on results.

**Comment by viktorstrate** [comment]
I can't see exactly why the database connection fails, did you change the environment variables after creating the containers initially? Also is there a particular reason why you changed the default database environment variables?

Remember to delete the volumes if you change your config with `docker-compose down -v`

**Comment by bhm** [comment]
> Also is there a particular reason why you changed the default database environment variables?

They are default for mariadb image container that this docker compose config is using.  Both prefixes are supported (though the MYSQL logic is mangled in the init script they are using).

>Remember to delete the volumes if you change your config with docker-compose down -v

I've started from scratch multiple times, with multiple configurations.
