### ISSUE TITLE
segmentation violation code

### ISSUE THREAD

**Issue by danmed** [photoview/photoview#497]
**Describe the bug**
When scanning, things cash and restart

```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1c8 pc=0xb28391]




goroutine 7682 [running]:


github.com/photoview/photoview/api/scanner.processVideo(0xc00011afc0, 0xc0002ddc78, 0xc000ee45d0, 0x0, 0xc000098c30, 0xfb8c00)


	/app/scanner/process_video.go:110 +0x1231


github.com/photoview/photoview/api/scanner.ProcessMedia(0xc00011afc0, 0xc000f21380, 0x0, 0x0, 0xc000dab200)


	/app/scanner/process_photo.go:82 +0xeb


github.com/photoview/photoview/api/scanner.scanAlbum.func2(0xc00011afc0, 0x0, 0x0)


	/app/scanner/scanner_album.go:118 +0xa5


gorm.io/gorm.(*DB).Transaction(0xc0000c5cb0, 0xc00056d2c0, 0x0, 0x0, 0x0, 0x0, 0x0)


	/go/pkg/mod/gorm.io/gorm@v1.21.6/finisher_api.go:556 +0x3da


github.com/photoview/photoview/api/scanner.scanAlbum(0xc00036f400, 0xc00029ec40, 0xc0000c5cb0)


	/app/scanner/scanner_album.go:117 +0x365


github.com/photoview/photoview/api/scanner.(*ScannerJob).Run(...)


	/app/scanner/queue.go:23


github.com/photoview/photoview/api/scanner.(*ScannerQueue).processQueue.func1(0xc000c54690, 0x146d400)


	/app/scanner/queue.go:132 +0x8d


created by github.com/photoview/photoview/api/scanner.(*ScannerQueue).processQueue
```

	/app/scanner/queue.go:130 +0x1bd

**Comment by burntcookie90** [comment]
https://github.com/photoview/photoview/issues/266 seems like it might be a dupe for this.
