### ISSUE TITLE
Crash with `invalid memory address or nil pointer dereference` during scan job

### ISSUE THREAD

**Issue by jhofker** [photoview/photoview#626]
**Describe the bug**
Running in Docker on Unraid. Photoview crashed with the following stacktrace while processing files. Last file it logged was a video (`.mov`)

```2022/01/06 17:24:26 Processing video: /photos/username/camera roll/20170101_012130000_iOS.MOV
panic: runtime error: invalid memory address or nil pointer dereference

[signal SIGSEGV: segmentation violation code=0x1 addr=0x1c8 pc=0xb2e931]

goroutine 44730 [running]:
github.com/photoview/photoview/api/scanner.processVideo(0xc000611cb0, 0xc00073fc78, 0xc000279d10, 0x0, 0xc000284dd0, 0xfc52a0)
/app/scanner/process_video.go:110 +0x1231
github.com/photoview/photoview/api/scanner.ProcessMedia(0xc000611cb0, 0xc002c93380, 0x0, 0x0, 0xc002329700)
/app/scanner/process_photo.go:82 +0xeb
github.com/photoview/photoview/api/scanner.scanAlbum.func2(0xc000611cb0, 0x0, 0x0)
/app/scanner/scanner_album.go:118 +0xa5
gorm.io/gorm.(*DB).Transaction(0xc0002aad80, 0xc000e24ba0, 0x0, 0x0, 0x0, 0x0, 0x0)
/go/pkg/mod/gorm.io/gorm@v1.21.6/finisher_api.go:556 +0x3da
github.com/photoview/photoview/api/scanner.scanAlbum(0xc000289c00, 0xc000274320, 0xc0002aad80)
/app/scanner/scanner_album.go:117 +0x365
github.com/photoview/photoview/api/scanner.(*ScannerJob).Run(...)
/app/scanner/queue.go:23
github.com/photoview/photoview/api/scanner.(*ScannerQueue).processQueue.func1(0xc000b06030, 0x147f600)
/app/scanner/queue.go:132 +0x8d
created by github.com/photoview/photoview/api/scanner.(*ScannerQueue).processQueue
/app/scanner/queue.go:130 +0x1bd
```

**To Reproduce**
1. Allow a scheduled scan to take place
2. Notice that the container is down (I wish I had more to give here)

**Expected behavior**
It doesn't crash.

**Screenshots**

**Your environment:**
Feel free to remove and add what you think might be useful.

 - Are you using Docker? yes
 - Database: MariaDB 10.6.5
 - Browser: n/a
 - Version: 2.3.9

**Additional context**
I have a significant number of photos and videos which could contribute to the issue.

**Comment by zeeshan-m** [comment]
I'm running into the same issue

**Comment by viktorstrate** [comment]
Does it only crash when running a periodic scan or does it also crash when the "Scan all" button is pressed?

**Comment by zeeshan-m** [comment]
@viktorstrate I've had it happen for both, both times I believe it crashed at an MOV

```
2022/01/15 19:06:02 Processing video: /photos/icloudpd/{PATH}/IMG_HEVC.MOV
panic: runtime error: invalid memory address or nil pointer dereference

[signal SIGSEGV: segmentation violation code=0x1 addr=0x1c8 pc=0xb2e931]

goroutine 116502 [running]:
github.com/photoview/photoview/api/scanner.processVideo(0xc001456120, 0xc0018ebc78, 0xc00212b1e0, 0x0, 0xc0000bd040, 0xfc52a0)
/app/scanner/process_video.go:110 +0x1231
github.com/photoview/photoview/api/scanner.ProcessMedia(0xc001456120, 0xc0022f0680, 0x0, 0x0, 0xc0004faf80)
/app/scanner/process_photo.go:82 +0xeb
github.com/photoview/photoview/api/scanner.scanAlbum.func2(0xc001456120, 0x0, 0x0)
/app/scanner/scanner_album.go:118 +0xa5
gorm.io/gorm.(*DB).Transaction(0xc000312120, 0xc000acef60, 0x0, 0x0, 0x0, 0x0, 0x0)
/go/pkg/mod/gorm.io/gorm@v1.21.6/finisher_api.go:556 +0x3da
github.com/photoview/photoview/api/scanner.scanAlbum(0xc000162000, 0xc0003e1ce0, 0xc000312120)
/app/scanner/scanner_album.go:117 +0x365
github.com/photoview/photoview/api/scanner.(*ScannerJob).Run(...)
/app/scanner/queue.go:23
github.com/photoview/photoview/api/scanner.(*ScannerQueue).processQueue.func1(0xc00153fe70, 0x147f600)
/app/scanner/queue.go:132 +0x8d
created by github.com/photoview/photoview/api/scanner.(*ScannerQueue).processQueue
/app/scanner/queue.go:130 +0x1bd
```

**Comment by zeeshan-m** [comment]
I started the container again to test if this was happening on the same file, and I believe it is. I'm not sure if this makes a difference, but the image / MOV in question is generated based on a live photo by ffmpeg via icloudpd (https://github.com/icloud-photos-downloader/icloud_photos_downloader).

```
2022/01/15 23:27:10 Processing photo: /photos/icloudpd/{PATH}/IMG_2081.HEIC
2022/01/15 23:27:10 Processing video: /photos/icloudpd/{PATH}/IMG_2081_HEVC.MOV
panic: runtime error: invalid memory address or nil pointer dereference

[signal SIGSEGV: segmentation violation code=0x1 addr=0x1c8 pc=0xb2e931]

goroutine 103431 [running]:
github.com/photoview/photoview/api/scanner.processVideo(0xc001bec990, 0xc0015f7c78, 0xc001be7090, 0x0, 0xc0002629c0, 0xfc52a0)
/app/scanner/process_video.go:110 +0x1231
github.com/photoview/photoview/api/scanner.ProcessMedia(0xc001bec990, 0xc001200ea0, 0x0, 0x0, 0xc001bc7400)
/app/scanner/process_photo.go:82 +0xeb
github.com/photoview/photoview/api/scanner.scanAlbum.func2(0xc001bec990, 0x0, 0x0)
/app/scanner/scanner_album.go:118 +0xa5
gorm.io/gorm.(*DB).Transaction(0xc000306ea0, 0xc001bee2a0, 0x0, 0x0, 0x0, 0x0, 0x0)
/go/pkg/mod/gorm.io/gorm@v1.21.6/finisher_api.go:556 +0x3da
github.com/photoview/photoview/api/scanner.scanAlbum(0xc0009f0800, 0xc0004d25a0, 0xc000306ea0)
/app/scanner/scanner_album.go:117 +0x365
github.com/photoview/photoview/api/scanner.(*ScannerJob).Run(...)
/app/scanner/queue.go:23
github.com/photoview/photoview/api/scanner.(*ScannerQueue).processQueue.func1(0xc001243050, 0x147f600)
/app/scanner/queue.go:132 +0x8d
created by github.com/photoview/photoview/api/scanner.(*ScannerQueue).processQueue
/app/scanner/queue.go:130 +0x1bd
```

**Comment by jhofker** [comment]
> Does it only crash when running a periodic scan or does it also crash when the "Scan all" button is pressed?

Like zeeshan, I've had it happen both ways. I don't download with icloudpd, but it's still what appears to be a live photo from an iOS device. If you're interested, I'll see if the file is something I can share?

**Comment by maxime-killinger** [comment]
Same problem here also for .MOV file from live photo

**Comment by fmnamado** [comment]
Hello,

I am having this problem also

```
2022/03/30 08:30:41 Processing video: /path/to/video/IMG_6389.MOV
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1c8 pc=0xaaf5f8]
goroutine 44997 [running]:
github.com/photoview/photoview/api/scanner.processVideo(0x4000354480, 0x40006f3c50, 0x400034ae60)
	/app/scanner/process_video.go:110 +0x12b8
github.com/photoview/photoview/api/scanner.ProcessMedia(0x4000354480, 0x4000a24d00)
	/app/scanner/process_photo.go:82 +0xa8
github.com/photoview/photoview/api/scanner.scanAlbum.func2(0x4000354480)
	/app/scanner/scanner_album.go:118 +0x78
gorm.io/gorm.(*DB).Transaction(0x400023f230, 0x40002662a0, {0x0, 0x0, 0x0})
	/go/pkg/mod/gorm.io/gorm@v1.22.5/finisher_api.go:574 +0x210
github.com/photoview/photoview/api/scanner.scanAlbum(0x4000775c00, 0x40006c8300, 0x400023f230)
	/app/scanner/scanner_album.go:117 +0x438
github.com/photoview/photoview/api/scanner.(*ScannerJob).Run(...)
	/app/scanner/queue.go:24
github.com/photoview/photoview/api/scanner.(*ScannerQueue).processQueue.func1(0x40019242a0, 0x134dfc0)
	/app/scanner/queue.go:133 +0x74
created by github.com/photoview/photoview/api/scanner.(*ScannerQueue).processQueue
	/app/scanner/queue.go:131 +0x194
2022/03/30 08:30:43 Starting Photoview...
2022/03/30 08:30:43 No .env file found
2022/03/30 08:30:43 Connecting to MYSQL database: photoview:photosecret@tcp(db:3306)/photoview?multiStatements=true&parseTime=true
2022/03/30 08:30:43 Initializing scanner queue with 1 workers
2022/03/30 08:30:43 Queue waiting
2022/03/30 08:30:43 Periodic scan interval changed: disabled
2022/03/30 08:30:43 Scan interval runner: Waiting for signal
2022/03/30 08:30:43 Scan interval runner: New ticker detected
2022/03/30 08:30:43 Scan interval runner: Waiting for signal
2022/03/30 08:30:44 Found executable worker: darktable (this is darktable-cli 3.8.0)
2022/03/30 08:30:44 Found executable worker: ffmpeg (ffmpeg version 4.4.1-3 Copyright (c) 2000-2021 the FFmpeg developers)
2022/03/30 08:30:44 Found exiftool
2022/03/30 08:30:44 Initializing face detector
2022/03/30 08:30:46 /app/scanner/face_detection/face_detector.go:56 SLOW SQL >= 200ms
[320.275ms] [rows:6718] SELECT * FROM `image_faces`
2022/03/30 08:30:46 Photoview API endpoint listening at http://photoview:80/api
2022/03/30 08:30:46 Photoview API public endpoint ready at /api
2022/03/30 08:30:46 Photoview UI public endpoint ready at /
2022/03/30 08:31:43 Did not find auth-token cookie
2022/03/30 08:31:43 POST 200 localhost/api/graphql 2.273937ms unauthenticated
2022/03/30 08:32:44 Did not find auth-token cookie
2022/03/30 08:32:44 POST 200 localhost/api/graphql 1.706789ms unauthenticated
2022/03/30 08:33:44 Did not find auth-token cookie
2022/03/30 08:33:44 POST 200 localhost/api/graphql 2.348219ms unauthenticated
2022/03/30 08:34:44 Did not find auth-token cookie
2022/03/30 08:34:44 POST 200 localhost/api/graphql 1.703672ms unauthenticated

```

Photoview Version

Release Version
2.3.12 ([0b9d04ef](https://github.com/photoview/photoview/commit/0b9d04eff2b6f896a70e8d081b6706dc4068f732))

Build date
2022-02-11T12:07:20Z

**Comment by loranger** [comment]
Same here : No more scan since I got my icloud files back using icloudpd

**Comment by DaCHack** [comment]
Same here: The issue for me were a range of GoPro videos on my Synology NAS that only contained the SoS stream, but no video or audio streams. These files were like 2KB small so easy to identify via filesize.
Not sure of you can handle such a specific case, but agree that there should be some general catch to pickup the ffmpeg error and avoid the crash.

I identified all affected files with the following command in the top node of my photo directory tree and moved them somewhere else:
`find . -type f -name '*.MP4' -size -10k ! -path '*/@eaDir/*'`
The last part behind "!" was only to avoid all the false positives in Synology's thumbnail folders "@eaDir" - you might not need it.

After this, scan seems to run through just fine.

**Comment by kkovaletp** [comment]
We need to debug this case from the code perspective and handle it correctly

**Comment by KingUdo** [comment]
I'm getting the same issue with am .mp4 file:

```photoview_1  | 2025/06/22 09:59:36 Processing video: /photos/2017_12_Südafrika/2017_12_08ce420b777ec74188a00f95acf24c7c48500620c7.mp4
photoview_1  | panic: runtime error: invalid memory address or nil pointer dereference
photoview_1  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x1e0 pc=0xbd9b20]
photoview_1  | 
photoview_1  | goroutine 27882 [running]:
photoview_1  | github.com/photoview/photoview/api/scanner/scanner_tasks/processing_tasks.ProcessVideoTask.ProcessMedia({{}}, {{0x10497e0?, 0x4000bb2bd0?}}, 0x40001b7200, {0x40003966f0, 0x13})
photoview_1  | 	/app/scanner/scanner_tasks/processing_tasks/process_video_task.go:75 +0x430
photoview_1  | github.com/photoview/photoview/api/scanner/scanner_tasks.scannerTasks.ProcessMedia({{}}, {{0x10497e0?, 0x4000bb2bd0?}}, 0x10497e0?, {0x40003966f0, 0x13})
photoview_1  | 	/app/scanner/scanner_tasks/scanner_tasks.go:128 +0x118
photoview_1  | github.com/photoview/photoview/api/scanner.scanMedia.func1({{0x10497e0?, 0x4000bb2bd0?}})
photoview_1  | 	/app/scanner/media_scan.go:23 +0x58
photoview_1  | github.com/photoview/photoview/api/scanner/scanner_task.TaskContext.DatabaseTransaction.func1(0x4001318810?)
photoview_1  | 	/app/scanner/scanner_task/scanner_task.go:73 +0x40
photoview_1  | gorm.io/gorm.(*DB).Transaction(0x4001318810, 0x400092c280, {0x0, 0x0, 0x0})
photoview_1  | 	/go/pkg/mod/gorm.io/gorm@v1.25.9/finisher_api.go:651 +0x1ec
photoview_1  | github.com/photoview/photoview/api/scanner/scanner_task.TaskContext.DatabaseTransaction({{0x10497e0?, 0x4000bb2bd0?}}, 0x4000a64230, {0x0, 0x0, 0x0})
photoview_1  | 	/app/scanner/scanner_task/scanner_task.go:72 +0xf0
photoview_1  | github.com/photoview/photoview/api/scanner.scanMedia({{0x10497e0?, 0x4000bb2bd0?}}, 0x4000378d00, 0x40001b7200, 0x195, 0x997)
photoview_1  | 	/app/scanner/media_scan.go:22 +0x13c
photoview_1  | github.com/photoview/photoview/api/scanner.ScanAlbum({{0x10497e0?, 0x40013188a0?}})
photoview_1  | 	/app/scanner/scanner_album.go:105 +0x24c
photoview_1  | github.com/photoview/photoview/api/scanner/scanner_queue.(*ScannerJob).Run(0x40016c77b8?, 0x7078e0?)
photoview_1  | 	/app/scanner/scanner_queue/queue.go:35 +0x28
photoview_1  | github.com/photoview/photoview/api/scanner/scanner_queue.(*ScannerQueue).processQueue.func1()
photoview_1  | 	/app/scanner/scanner_queue/queue.go:147 +0x64
photoview_1  | created by github.com/photoview/photoview/api/scanner/scanner_queue.(*ScannerQueue).processQueue
photoview_1  | 	/app/scanner/scanner_queue/queue.go:145 +0x14c
```

Looking at the .mp4 file I would guess that there was a recording/transfer error. 
I guess what we might need is some cleaner error handling in how the file is processes/ have a check if the file is corrupted or not.

Is anyone already looking into this issue?

**Comment by kkovaletp** [comment]
@KingUdo, thanks for the report.

Can you please provide the environment description?
- Direct installation or Docker Compose services?
- Which version is used? It could be found on the Settings page, or the tag name for the `photoview` image in the compose file, or the branch/tag name from which it was cloned for the direct installation on the host.
- What is the difference between your current configuration and the default recommended one? What did you change in the configs? You can share your configs here with masked sensitive/secret values.

Could you please share the media file causing the panic in an archive without a password (e.g., zip, 7z)?

Thanks in advance, as this is not a reproducible issue on our side, and since you've reproduced it, this is a good opportunity for us to find the root cause.

**Comment by KingUdo** [comment]
For sure!
I'm running the photoview docker using the latest version from "viktorstrate/photoview:2".
I did not change anything from the default deployment.

[0b53a686741372e213825275d12ad28086ce040b.mp4.zip](https://github.com/user-attachments/files/20853238/0b53a686741372e213825275d12ad28086ce040b.mp4.zip)

**Comment by kkovaletp** [comment]
@KingUdo, thanks for the details.
1st note: we've migrated to our new Docker registry: `photoview/photoview`, so I'd suggest you to update your compose file and switch to the new registry. Even while you use the released version, this image is refreshed weekly to get newer base image and latest available OS packages and libraries, so you might still benefit from pulling new version of the same image from the new registry.
2nd: I scanned your file by the `photoview/photoview:2` image and didn't get the panic/crach. Instead, the next error was reported:
```
2025/06/22 19:10:40 ERROR: Error scanning media for album (3) file (/photos/main/corrupted.mp4): process media database transaction: process media (/photos/main/corrupted.mp4): failed to generate thumbnail for video (corrupted.mp4): encoding video using: /usr/bin/ffmpeg: exit status 1
```
3rd: I scanned your file by the `photoview/photoview:master` version, containing the latest merged code with all new features and fixes, and here is the error, it reports about the file now:
```
2025/06/22 18:51:22 ERROR: Error scanning media for album (3) file (/photos/main/corrupted.mp4): process media database transaction: process media (/photos/main/corrupted.mp4): failed to generate thumbnail for video (corrupted.mp4): encoding video thumbnail with "/usr/local/bin/ffmpeg" [-ss 1 -i /photos/main/corrupted.mp4 -vframes 1 -an -vf scale='min(1024,iw)':'min(1024,ih)':force_original_aspect_ratio=decrease:force_divisible_by=2 /home/photoview/media-cache/3/72/video_thumb_corrupted_mp4_kBBVxSmr.jpg] error: exit status 183
```
It still not the best one, but it indicates the file and the problem now, and what is more important: there is no panic or crash.

I don't know what caused the panic/crash in your case, but I'd suggest to try the `master` image: there are good chances that you won't see it with this image and also, you'll get a lot of new features, improvements, and fixes. While this image is the rolling one and it might contain some new defects, it is stable enough to be used by end users.
Please let us know the results.

**Comment by kkovaletp** [comment]
@googollee, while working on the new queue, please check this old bug report. Most probably, it was already handled by previous changes, but it is better to double-check before closing it...

**Comment by googollee** [comment]
The queue doesn't relate with tasks. Anyhow, I'll check current code.

**Comment by googollee** [comment]
The log in https://github.com/photoview/photoview/issues/626#issue-1095906976, https://github.com/photoview/photoview/issues/626#issuecomment-1013805443, https://github.com/photoview/photoview/issues/626#issuecomment-1013821079 and https://github.com/photoview/photoview/issues/626#issuecomment-1082823990 are pretty old, which doesn't exist in current code.

The log in https://github.com/photoview/photoview/issues/626#issuecomment-2994106925 already fixed, see https://github.com/photoview/photoview/issues/626#issuecomment-2994301294. It's not ideally, but it doesn't crash.

I'm closing this issue. Please submit a **new** one if there are more crashes.
