### ISSUE TITLE
Crash on importing HEIC images

### ISSUE THREAD

**Issue by larsxschneider** [photoview/photoview#740]
**Describe the bug**
Importing a large  (15.8 MB / 16382 × 3794 pixels) HEIF image on my server with ARM CPU and 8GB RAM results in the following crash:

```
2022/08/20 13:26:17 Processing photo: /photos/foobar.HEIC
runtime: out of memory: cannot allocate 251658240-byte block (863109120 in use)
fatal error: out of memory

goroutine 237700 [running]:
runtime.throw({0x9f3fae, 0xd})
	/usr/lib/go-1.18/src/runtime/panic.go:992 +0x5c fp=0xc11d850 sp=0xc11d83c pc=0x9334c
runtime.(*mcache).allocLarge(0x74b40538, 0xed18970, 0x1)
	/usr/lib/go-1.18/src/runtime/mcache.go:215 +0x1e4 fp=0xc11d878 sp=0xc11d850 pc=0x711c8
runtime.mallocgc(0xed18970, 0x954398, 0x1)
	/usr/lib/go-1.18/src/runtime/malloc.go:1096 +0x690 fp=0xc11d8b8 sp=0xc11d878 pc=0x6720c
runtime.makeslice(0x954398, 0xed18970, 0xed18970)
	/usr/lib/go-1.18/src/runtime/slice.go:103 +0xac fp=0xc11d8cc sp=0xc11d8b8 pc=0xac6f8
github.com/strukturag/libheif/go/heif.(*Image).GetImage(0xc0f66a0)
	/go/pkg/mod/github.com/strukturag/libheif@v1.12.0/go/heif/heif.go:828 +0x5fc fp=0xc11d9e8 sp=0xc11d8cc pc=0x74febc
github.com/strukturag/libheif/go/heif.decodeImage({0xaf587c, 0x4b5b4a0})
	/go/pkg/mod/github.com/strukturag/libheif@v1.12.0/go/heif/heif.go:1381 +0x98 fp=0xc11da08 sp=0xc11d9e8 pc=0x751e78
image.Decode({0xaf62b8, 0x8749fd0})
	/usr/lib/go-1.18/src/image/format.go:93 +0x178 fp=0xc11da7c sp=0xc11da08 pc=0x40bfec
github.com/photoview/photoview/api/scanner/media_encoding.(*EncodeMediaData).decodeImage(0x638ae88, {0x6a84e70, 0x2c})
	/app/scanner/media_encoding/encode_photo.go:154 +0x230 fp=0xc11dad8 sp=0xc11da7c pc=0x752fac
github.com/photoview/photoview/api/scanner/media_encoding.(*EncodeMediaData).photoImage(0x638ae88)
	/app/scanner/media_encoding/encode_photo.go:130 +0x58 fp=0xc11db24 sp=0xc11dad8 pc=0x752bf0
github.com/photoview/photoview/api/scanner/media_encoding.(*EncodeMediaData).EncodeHighRes(0x638ae88, {0xaff3f90, 0x42})
	/app/scanner/media_encoding/encode_photo.go:106 +0x228 fp=0xc11dc44 sp=0xc11db24 pc=0x752b0c
github.com/photoview/photoview/api/scanner/scanner_tasks/processing_tasks.generateSaveHighResJPEG(0xbdde3c0, 0x58f3f00, 0x638ae88, {0x6a85860, 0x2d}, {0xaff3f90, 0x42}, 0x0)
	/app/scanner/scanner_tasks/processing_tasks/processing_functions.go:16 +0x74 fp=0xc11dc9c sp=0xc11dc44 pc=0x7799b8
github.com/photoview/photoview/api/scanner/scanner_tasks/processing_tasks.ProcessPhotoTask.ProcessMedia({{}}, {{0xaf9b98, 0x638afc0}}, 0x638ae88, {0xb007d40, 0x14})
	/app/scanner/scanner_tasks/processing_tasks/process_photo_task.go:73 +0x76c fp=0xc11dd7c sp=0xc11dc9c pc=0x776ef0
github.com/photoview/photoview/api/scanner/scanner_tasks/processing_tasks.(*ProcessPhotoTask).ProcessMedia(0xfac100, {{0xaf9b98, 0x638afc0}}, 0x638ae88, {0xb007d40, 0x14})
	<autogenerated>:1 +0x54 fp=0xc11dda8 sp=0xc11dd7c pc=0x77c33c
github.com/photoview/photoview/api/scanner/scanner_tasks.scannerTasks.ProcessMedia({{}}, {{0xaf9b98, 0x638afc0}}, 0x638ae88, {0xb007d40, 0x14})
	/app/scanner/scanner_tasks/scanner_tasks.go:128 +0x13c fp=0xc11de04 sp=0xc11dda8 pc=0x77e088
github.com/photoview/photoview/api/scanner.processMedia({{0xaf9b98, 0x638afc0}}, 0x638ae88)
	/app/scanner/scanner_album.go:204 +0xb0 fp=0xc11de30 sp=0xc11de04 pc=0x784954
github.com/photoview/photoview/api/scanner.ScanAlbum.func1({{0xaf9b98, 0x638afc0}})
	/app/scanner/scanner_album.go:115 +0x4c fp=0xc11de70 sp=0xc11de30 pc=0x783dfc
github.com/photoview/photoview/api/scanner/scanner_task.TaskContext.DatabaseTransaction.func1(0xbdde2a0)
	/app/scanner/scanner_task/scanner_task.go:73 +0x50 fp=0xc11de8c sp=0xc11de70 pc=0x755d78
gorm.io/gorm.(*DB).Transaction(0x2c59b60, 0x4aa6c40, {0x0, 0x0, 0x0})
	/go/pkg/mod/gorm.io/gorm@v1.23.7/finisher_api.go:606 +0x24c fp=0xc11df0c sp=0xc11de8c pc=0x3f6834
github.com/photoview/photoview/api/scanner/scanner_task.TaskContext.DatabaseTransaction({{0xaf9b98, 0x3c2e138}}, 0x638aea0, {0x0, 0x0, 0x0})
	/app/scanner/scanner_task/scanner_task.go:72 +0xe4 fp=0xc11df30 sp=0xc11df0c pc=0x755cd0
github.com/photoview/photoview/api/scanner.ScanAlbum({{0xaf9b98, 0x26b8c18}})
	/app/scanner/scanner_album.go:114 +0x4b0 fp=0xc11dfbc sp=0xc11df30 pc=0x783b80
github.com/photoview/photoview/api/scanner/scanner_queue.(*ScannerJob).Run(...)
	/app/scanner/scanner_queue/queue.go:35
github.com/photoview/photoview/api/scanner/scanner_queue.(*ScannerQueue).processQueue.func1()
	/app/scanner/scanner_queue/queue.go:144 +0x78 fp=0xc11dfec sp=0xc11dfbc pc=0x789ae4
runtime.goexit()
	/usr/lib/go-1.18/src/runtime/asm_arm.s:824 +0x4 fp=0xc11dfec sp=0xc11dfec pc=0xc5754
created by github.com/photoview/photoview/api/scanner/scanner_queue.(*ScannerQueue).processQueue
	/app/scanner/scanner_queue/queue.go:142 +0x114

goroutine 1 [IO wait]:
internal/poll.runtime_pollWait(0x640437b0, 0x72)
	/usr/lib/go-1.18/src/runtime/netpoll.go:302 +0x54
internal/poll.(*pollDesc).wait(0x22ca794, 0x72, 0x0)
	/usr/lib/go-1.18/src/internal/poll/fd_poll_runtime.go:83 +0x30
internal/poll.(*pollDesc).waitRead(...)
	/usr/lib/go-1.18/src/internal/poll/fd_poll_runtime.go:88
internal/poll.(*FD).Accept(0x22ca780)
	/usr/lib/go-1.18/src/internal/poll/fd_unix.go:614 +0x248
net.(*netFD).accept(0x22ca780)
	/usr/lib/go-1.18/src/net/fd_unix.go:172 +0x20
net.(*TCPListener).accept(0x200e020)
	/usr/lib/go-1.18/src/net/tcpsock_posix.go:139 +0x20
net.(*TCPListener).Accept(0x200e020)
	/usr/lib/go-1.18/src/net/tcpsock.go:288 +0x30
net/http.(*Server).Serve(0x22c0120, {0xaf92cc, 0x200e020})
	/usr/lib/go-1.18/src/net/http/server.go:3039 +0x344
net/http.(*Server).ListenAndServe(0x22c0120)
	/usr/lib/go-1.18/src/net/http/server.go:2968 +0xa4
net/http.ListenAndServe(...)
	/usr/lib/go-1.18/src/net/http/server.go:3222
main.main()
	/app/server.go:122 +0xe10

goroutine 5 [select, 1019 minutes]:
database/sql.(*DB).connectionOpener(0x22c05a0, {0xaf9b38, 0x22ce0f0})
	/usr/lib/go-1.18/src/database/sql/sql.go:1226 +0x9c
created by database/sql.OpenDB
	/usr/lib/go-1.18/src/database/sql/sql.go:794 +0x188

goroutine 40 [IO wait, 499 minutes]:
internal/poll.runtime_pollWait(0x6404384c, 0x72)
	/usr/lib/go-1.18/src/runtime/netpoll.go:302 +0x54
internal/poll.(*pollDesc).wait(0x21ae214, 0x72, 0x1)
	/usr/lib/go-1.18/src/internal/poll/fd_poll_runtime.go:83 +0x30
internal/poll.(*pollDesc).waitRead(...)
	/usr/lib/go-1.18/src/internal/poll/fd_poll_runtime.go:88
internal/poll.(*FD).Read(0x21ae200, {0x24f8000, 0x8000, 0x8000})
	/usr/lib/go-1.18/src/internal/poll/fd_unix.go:167 +0x210
os.(*File).read(...)
	/usr/lib/go-1.18/src/os/file_posix.go:31
os.(*File).Read(0x2010238, {0x24f8000, 0x8000, 0x8000})
	/usr/lib/go-1.18/src/os/file.go:119 +0x70
io.copyBuffer({0xaf5fc0, 0x2010200}, {0xaf62b8, 0x2010238}, {0x0, 0x0, 0x0})
	/usr/lib/go-1.18/src/io/io.go:426 +0x1f8
io.Copy(...)
	/usr/lib/go-1.18/src/io/io.go:385
os/exec.(*Cmd).writerDescriptor.func1()
	/usr/lib/go-1.18/src/os/exec/exec.go:311 +0x4c
os/exec.(*Cmd).Start.func1(0x200e0b0)
	/usr/lib/go-1.18/src/os/exec/exec.go:444 +0x24
created by os/exec.(*Cmd).Start
	/usr/lib/go-1.18/src/os/exec/exec.go:443 +0x6dc

goroutine 39 [chan receive, 1019 minutes]:
github.com/photoview/photoview/api/scanner/periodic_scanner.scanIntervalRunner()
	/app/scanner/periodic_scanner/periodic_scanner.go:88 +0x150
created by github.com/photoview/photoview/api/scanner/periodic_scanner.InitializePeriodicScanner
	/app/scanner/periodic_scanner/periodic_scanner.go:48 +0x114

goroutine 22 [chan receive, 537 minutes]:
github.com/photoview/photoview/api/scanner/scanner_queue.(*ScannerQueue).startBackgroundWorker(0xf98918)
	/app/scanner/scanner_queue/queue.go:101 +0xdc
created by github.com/photoview/photoview/api/scanner/scanner_queue.InitializeScannerQueue
	/app/scanner/scanner_queue/queue.go:78 +0x19c

goroutine 402966 [chan receive]:
database/sql.(*Tx).awaitDone(0x2125020)
	/usr/lib/go-1.18/src/database/sql/sql.go:2189 +0x3c
created by database/sql.(*DB).beginDC
	/usr/lib/go-1.18/src/database/sql/sql.go:1903 +0x200
```

**Your environment:**
Feel free to remove and add what you think might be useful.

 - Are you using Docker? yes
 - Database: Postgres
 - Browser: -
 - Version: 2.3.13 ([446ef9a4](https://github.com/photoview/photoview/commit/446ef9a46485bd18bb1c6890d485344786a4e90c))

**Additional context**
I believe the error happens in the `libheif` library and therefore I filed there a bug as well: https://github.com/strukturag/libheif/issues/665

Maybe photoview could guard against this error?

**Comment by kkovaletp** [comment]
@larsxschneider, thanks for your report and linking the issue, submitted it for the libheif project as well.
I've downloaded the example, you shared there and successfully imported it into my testing instance of Photoview with no errors reported. I don't have the ARM platform and test it on the x64 one, but I assume that this is not so important for this case.
After the successful import, I got into the `photoview` container and checked the version of the libheif package: now it is 1.15.1-1.
With this, I assume that the defect was fixed in this new version, even though the issue in the libheif project is not updated.

So, please let me know if it works fine for you if you use the `photoview:master` image. Then I can close it as completed.

**Comment by kkovaletp** [comment]
The next help from the community is wanted and would be appreciated:
If someone hosting Photoview (from the `master` branch) on an ARM platform with a relatively low amount of memory, please test the importing of the image, attached to this ticket, and let us know whether the issue still exists there.

**Comment by kkovaletp** [comment]
Closing the issue as completed after updating the lib version in the project.
